In [11]:
# bring in pandas
import pandas as pd

In [12]:
# load data, text file with tab delimiter
df = pd.read_csv('edited_data.txt', delimiter = '\t')
df

,Day,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,1,9:25,10:12,11:19,12:40,13:53,14:48,14:56,14:14,13:03,11:47,10:30,9:34
1,2,9:26,10:14,11:21,12:42,13:55,14:49,14:55,14:12,13:01,11:44,10:28,9:33
2,3,9:27,10:16,11:24,12:45,13:58,14:50,14:55,14:10,12:58,11:41,10:25,9:32
3,4,9:28,10:18,11:26,12:47,14:00,14:51,14:54,14:08,12:56,11:39,10:23,9:31
4,5,9:29,10:20,11:29,12:50,14:02,14:52,14:53,14:06,12:53,11:36,10:21,9:30
5,6,9:30,10:23,11:32,12:52,14:04,14:53,14:52,14:04,12:51,11:34,10:19,9:29
6,7,9:31,10:25,11:34,12:55,14:06,14:53,14:51,14:02,12:48,11:31,10:16,9:28
7,8,9:32,10:27,11:37,12:58,14:08,14:54,14:51,14:00,12:46,11:29,10:14,9:27
8,9,9:33,10:29,11:39,13:00,14:10,14:55,14:50,13:58,12:43,11:26,10:12,9:26
9,10,9:34,10:32,11:42,13:03,14:12,14:56,14:48,13:55,12:41,11:24,10:10,9:26
10,11,9:35,10:34,11:45,13:05,14:14,14:56,14:47,13:53,12:38,11:21,10:08,9:25
11,12,9:36,10:36,11:47,13:08,14:16,14:57,14:46,13:51,12:36,11:18,10:06,9:24
12,13,9:38,10:39,11:50,13:10,14:18,14:57,14:45,13:49,12:33,11:16,10:04,9:24
13,14,9:39,10:41,11:52,13:13,14:20,14:58,14:44,13:47,12:30,11:13,10:02,9:23
14,15,9:41,10:44,11:55,13:15,14:22,14:58,14:42,13:44,12:28,11:11,10:00,9:23
15,16,9:42,10:46,11:58,13:18,14:24,14:58,14:41,13:42,12:25,11:08,9:58,9:22
16,17,9:44,10:48,12:00,13:20,14:26,14:59,14:40,13:40,12:23,11:06,9:56,9:22
17,18,9:45,10:51,12:03,13:23,14:27,14:59,14:38,13:37,12:20,11:03,9:54,9:22
18,19,9:47,10:53,12:06,13:25,14:29,14:59,14:37,13:35,12:18,11:01,9:53,9:22
19,20,9:49,10:56,12:08,13:28,14:31,14:59,14:35,13:33,12:15,10:58,9:51,9:22
20,21,9:50,10:58,12:11,13:30,14:32,14:59,14:34,13:30,12:12,10:56,9:49,9:21
21,22,9:52,11:01,12:13,13:32,14:34,14:59,14:32,13:28,12:10,10:54,9:48,9:21
22,23,9:54,11:03,12:16,13:35,14:36,14:59,14:30,13:26,12:07,10:51,9:46,9:22
23,24,9:56,11:06,12:19,13:37,14:37,14:59,14:29,13:23,12:05,10:49,9:44,9:22
24,25,9:58,11:08,12:21,13:39,14:39,14:59,14:27,13:21,12:02,10:46,9:43,9:22
25,26,9:59,11:11,12:24,13:42,14:40,14:58,14:25,13:18,12:00,10:44,9:41,9:22
26,27,10:01,11:14,12:26,13:44,14:41,14:58,14:24,13:16,11:57,10:41,9:40,9:22
27,28,10:03,11:16,12:29,13:46,14:43,14:58,14:22,13:13,11:54,10:39,9:38,9:23
28,29,10:05,NaN,12:32,13:49,14:44,14:57,14:20,13:11,11:52,10:37,9:37,9:23
29,30,10:07,NaN,12:34,13:51,14:45,14:57,14:18,13:08,11:49,10:34,9:36,9:24
30,31,10:09,NaN,12:37,NaN,14:46,NaN,14:16,13:06,NaN,10:32,NaN,9:24

In [13]:
# make "Day" the index
df.set_index('Day', inplace=True)
df

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Day,,,,,,,,,,,,
1,9:25,10:12,11:19,12:40,13:53,14:48,14:56,14:14,13:03,11:47,10:30,9:34
2,9:26,10:14,11:21,12:42,13:55,14:49,14:55,14:12,13:01,11:44,10:28,9:33
3,9:27,10:16,11:24,12:45,13:58,14:50,14:55,14:10,12:58,11:41,10:25,9:32
4,9:28,10:18,11:26,12:47,14:00,14:51,14:54,14:08,12:56,11:39,10:23,9:31
5,9:29,10:20,11:29,12:50,14:02,14:52,14:53,14:06,12:53,11:36,10:21,9:30
6,9:30,10:23,11:32,12:52,14:04,14:53,14:52,14:04,12:51,11:34,10:19,9:29
7,9:31,10:25,11:34,12:55,14:06,14:53,14:51,14:02,12:48,11:31,10:16,9:28
8,9:32,10:27,11:37,12:58,14:08,14:54,14:51,14:00,12:46,11:29,10:14,9:27
9,9:33,10:29,11:39,13:00,14:10,14:55,14:50,13:58,12:43,11:26,10:12,9:26
10,9:34,10:32,11:42,13:03,14:12,14:56,14:48,13:55,12:41,11:24,10:10,9:26
11,9:35,10:34,11:45,13:05,14:14,14:56,14:47,13:53,12:38,11:21,10:08,9:25
12,9:36,10:36,11:47,13:08,14:16,14:57,14:46,13:51,12:36,11:18,10:06,9:24
13,9:38,10:39,11:50,13:10,14:18,14:57,14:45,13:49,12:33,11:16,10:04,9:24
14,9:39,10:41,11:52,13:13,14:20,14:58,14:44,13:47,12:30,11:13,10:02,9:23
15,9:41,10:44,11:55,13:15,14:22,14:58,14:42,13:44,12:28,11:11,10:00,9:23
16,9:42,10:46,11:58,13:18,14:24,14:58,14:41,13:42,12:25,11:08,9:58,9:22
17,9:44,10:48,12:00,13:20,14:26,14:59,14:40,13:40,12:23,11:06,9:56,9:22
18,9:45,10:51,12:03,13:23,14:27,14:59,14:38,13:37,12:20,11:03,9:54,9:22
19,9:47,10:53,12:06,13:25,14:29,14:59,14:37,13:35,12:18,11:01,9:53,9:22
20,9:49,10:56,12:08,13:28,14:31,14:59,14:35,13:33,12:15,10:58,9:51,9:22
21,9:50,10:58,12:11,13:30,14:32,14:59,14:34,13:30,12:12,10:56,9:49,9:21
22,9:52,11:01,12:13,13:32,14:34,14:59,14:32,13:28,12:10,10:54,9:48,9:21
23,9:54,11:03,12:16,13:35,14:36,14:59,14:30,13:26,12:07,10:51,9:46,9:22
24,9:56,11:06,12:19,13:37,14:37,14:59,14:29,13:23,12:05,10:49,9:44,9:22
25,9:58,11:08,12:21,13:39,14:39,14:59,14:27,13:21,12:02,10:46,9:43,9:22
26,9:59,11:11,12:24,13:42,14:40,14:58,14:25,13:18,12:00,10:44,9:41,9:22
27,10:01,11:14,12:26,13:44,14:41,14:58,14:24,13:16,11:57,10:41,9:40,9:22
28,10:03,11:16,12:29,13:46,14:43,14:58,14:22,13:13,11:54,10:39,9:38,9:23
29,10:05,NaN,12:32,13:49,14:44,14:57,14:20,13:11,11:52,10:37,9:37,9:23
30,10:07,NaN,12:34,13:51,14:45,14:57,14:18,13:08,11:49,10:34,9:36,9:24
31,10:09,NaN,12:37,NaN,14:46,NaN,14:16,13:06,NaN,10:32,NaN,9:24

In [14]:
# make sure all columns are text
df.dtypes

Jan    object
Feb    object
Mar    object
Apr    object
May    object
Jun    object
Jul    object
Aug    object
Sep    object
Oct    object
Nov    object
Dec    object
dtype: object

In [15]:
# double check
type(df.iloc[3][3])

str

In [23]:
# create function
def decimal_time(t):
    try:
        t = t.split(':')
        hrs = float(t[0])
        min = float(t[1]) / 60
        return str(round(hrs + min, 3))
    except:
        return '0'

In [18]:
cols = list(df.columns)

In [24]:
# test function, return as string
decimal_time('12:28')

'12.467'

In [25]:
cols

['Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'Oct',
 'Nov',
 'Dec']

In [28]:
for col in cols:
    df[col] = df[col].apply(decimal_time)

In [29]:
df

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Day,,,,,,,,,,,,
1,9.417,10.2,11.317,12.667,13.883,14.8,14.933,14.233,13.05,11.783,10.5,9.567
2,9.433,10.233,11.35,12.7,13.917,14.817,14.917,14.2,13.017,11.733,10.467,9.55
3,9.45,10.267,11.4,12.75,13.967,14.833,14.917,14.167,12.967,11.683,10.417,9.533
4,9.467,10.3,11.433,12.783,14.0,14.85,14.9,14.133,12.933,11.65,10.383,9.517
5,9.483,10.333,11.483,12.833,14.033,14.867,14.883,14.1,12.883,11.6,10.35,9.5
6,9.5,10.383,11.533,12.867,14.067,14.883,14.867,14.067,12.85,11.567,10.317,9.483
7,9.517,10.417,11.567,12.917,14.1,14.883,14.85,14.033,12.8,11.517,10.267,9.467
8,9.533,10.45,11.617,12.967,14.133,14.9,14.85,14.0,12.767,11.483,10.233,9.45
9,9.55,10.483,11.65,13.0,14.167,14.917,14.833,13.967,12.717,11.433,10.2,9.433
10,9.567,10.533,11.7,13.05,14.2,14.933,14.8,13.917,12.683,11.4,10.167,9.433
11,9.583,10.567,11.75,13.083,14.233,14.933,14.783,13.883,12.633,11.35,10.133,9.417
12,9.6,10.6,11.783,13.133,14.267,14.95,14.767,13.85,12.6,11.3,10.1,9.4
13,9.633,10.65,11.833,13.167,14.3,14.95,14.75,13.817,12.55,11.267,10.067,9.4
14,9.65,10.683,11.867,13.217,14.333,14.967,14.733,13.783,12.5,11.217,10.033,9.383
15,9.683,10.733,11.917,13.25,14.367,14.967,14.7,13.733,12.467,11.183,10.0,9.383
16,9.7,10.767,11.967,13.3,14.4,14.967,14.683,13.7,12.417,11.133,9.967,9.367
17,9.733,10.8,12.0,13.333,14.433,14.983,14.667,13.667,12.383,11.1,9.933,9.367
18,9.75,10.85,12.05,13.383,14.45,14.983,14.633,13.617,12.333,11.05,9.9,9.367
19,9.783,10.883,12.1,13.417,14.483,14.983,14.617,13.583,12.3,11.017,9.883,9.367
20,9.817,10.933,12.133,13.467,14.517,14.983,14.583,13.55,12.25,10.967,9.85,9.367
21,9.833,10.967,12.183,13.5,14.533,14.983,14.567,13.5,12.2,10.933,9.817,9.35
22,9.867,11.017,12.217,13.533,14.567,14.983,14.533,13.467,12.167,10.9,9.8,9.35
23,9.9,11.05,12.267,13.583,14.6,14.983,14.5,13.433,12.117,10.85,9.767,9.367
24,9.933,11.1,12.317,13.617,14.617,14.983,14.483,13.383,12.083,10.817,9.733,9.367
25,9.967,11.133,12.35,13.65,14.65,14.983,14.45,13.35,12.033,10.767,9.717,9.367
26,9.983,11.183,12.4,13.7,14.667,14.967,14.417,13.3,12.0,10.733,9.683,9.367
27,10.017,11.233,12.433,13.733,14.683,14.967,14.4,13.267,11.95,10.683,9.667,9.367
28,10.05,11.267,12.483,13.767,14.717,14.967,14.367,13.217,11.9,10.65,9.633,9.383
29,10.083,0,12.533,13.817,14.733,14.95,14.333,13.183,11.867,10.617,9.617,9.383
30,10.117,0,12.567,13.85,14.75,14.95,14.3,13.133,11.817,10.567,9.6,9.4
31,10.15,0,12.617,0,14.767,0,14.267,13.1,0,10.533,0,9.4

In [30]:
df.dtypes

Jan    object
Feb    object
Mar    object
Apr    object
May    object
Jun    object
Jul    object
Aug    object
Sep    object
Oct    object
Nov    object
Dec    object
dtype: object

In [31]:
df = df.astype("float")
df.dtypes

Jan    float64
Feb    float64
Mar    float64
Apr    float64
May    float64
Jun    float64
Jul    float64
Aug    float64
Sep    float64
Oct    float64
Nov    float64
Dec    float64
dtype: object

In [32]:
df

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
Day,,,,,,,,,,,,
1,9.417,10.200,11.317,12.667,13.883,14.800,14.933,14.233,13.050,11.783,10.500,9.567
2,9.433,10.233,11.350,12.700,13.917,14.817,14.917,14.200,13.017,11.733,10.467,9.550
3,9.450,10.267,11.400,12.750,13.967,14.833,14.917,14.167,12.967,11.683,10.417,9.533
4,9.467,10.300,11.433,12.783,14.000,14.850,14.900,14.133,12.933,11.650,10.383,9.517
5,9.483,10.333,11.483,12.833,14.033,14.867,14.883,14.100,12.883,11.600,10.350,9.500
6,9.500,10.383,11.533,12.867,14.067,14.883,14.867,14.067,12.850,11.567,10.317,9.483
7,9.517,10.417,11.567,12.917,14.100,14.883,14.850,14.033,12.800,11.517,10.267,9.467
8,9.533,10.450,11.617,12.967,14.133,14.900,14.850,14.000,12.767,11.483,10.233,9.450
9,9.550,10.483,11.650,13.000,14.167,14.917,14.833,13.967,12.717,11.433,10.200,9.433
10,9.567,10.533,11.700,13.050,14.200,14.933,14.800,13.917,12.683,11.400,10.167,9.433
11,9.583,10.567,11.750,13.083,14.233,14.933,14.783,13.883,12.633,11.350,10.133,9.417
12,9.600,10.600,11.783,13.133,14.267,14.950,14.767,13.850,12.600,11.300,10.100,9.400
13,9.633,10.650,11.833,13.167,14.300,14.950,14.750,13.817,12.550,11.267,10.067,9.400
14,9.650,10.683,11.867,13.217,14.333,14.967,14.733,13.783,12.500,11.217,10.033,9.383
15,9.683,10.733,11.917,13.250,14.367,14.967,14.700,13.733,12.467,11.183,10.000,9.383
16,9.700,10.767,11.967,13.300,14.400,14.967,14.683,13.700,12.417,11.133,9.967,9.367
17,9.733,10.800,12.000,13.333,14.433,14.983,14.667,13.667,12.383,11.100,9.933,9.367
18,9.750,10.850,12.050,13.383,14.450,14.983,14.633,13.617,12.333,11.050,9.900,9.367
19,9.783,10.883,12.100,13.417,14.483,14.983,14.617,13.583,12.300,11.017,9.883,9.367
20,9.817,10.933,12.133,13.467,14.517,14.983,14.583,13.550,12.250,10.967,9.850,9.367
21,9.833,10.967,12.183,13.500,14.533,14.983,14.567,13.500,12.200,10.933,9.817,9.350
22,9.867,11.017,12.217,13.533,14.567,14.983,14.533,13.467,12.167,10.900,9.800,9.350
23,9.900,11.050,12.267,13.583,14.600,14.983,14.500,13.433,12.117,10.850,9.767,9.367
24,9.933,11.100,12.317,13.617,14.617,14.983,14.483,13.383,12.083,10.817,9.733,9.367
25,9.967,11.133,12.350,13.650,14.650,14.983,14.450,13.350,12.033,10.767,9.717,9.367
26,9.983,11.183,12.400,13.700,14.667,14.967,14.417,13.300,12.000,10.733,9.683,9.367
27,10.017,11.233,12.433,13.733,14.683,14.967,14.400,13.267,11.950,10.683,9.667,9.367
28,10.050,11.267,12.483,13.767,14.717,14.967,14.367,13.217,11.900,10.650,9.633,9.383
29,10.083,0.000,12.533,13.817,14.733,14.950,14.333,13.183,11.867,10.617,9.617,9.383
30,10.117,0.000,12.567,13.850,14.750,14.950,14.300,13.133,11.817,10.567,9.600,9.400
31,10.150,0.000,12.617,0.000,14.767,0.000,14.267,13.100,0.000,10.533,0.000,9.400